services: 
    user-service:
        image: notebookum-user:latest
        restart: unless-stopped
        # LOAD BALANCER PATTERN
        deploy:
            replicas: 2
        networks:
            - notebookum-network
        labels:
            # Traefik habilitación
            - "traefik.enable=true"
            
            # Router configuration
            - "traefik.http.routers.user-service.rule=Host(`user.universidad.localhost`)"
            - "traefik.http.routers.user-service.service=user-service"
            
            # Service configuration
            - "traefik.http.services.user-service.loadbalancer.server.port=5000"
            
            # CIRCUIT BREAKER PATTERN - Detección de errores de red
            - "traefik.http.middlewares.user-service-cb.circuitbreaker.expression=NetworkErrorRatio() > 0.5"
            
            # LATENCY PATTERN - Control de latencia máxima
            - "traefik.http.middlewares.user-service-latency.timeout.request=10s"
            
            # BULKHEAD PATTERN - Control de concurrencia
            - "traefik.http.middlewares.user-service-bulkhead.inflightreq.amount=30"
            
            # Aplicar middlewares al router
            - "traefik.http.routers.user-service.middlewares=user-service-cb,user-service-latency,user-service-bulkhead"
        
        environment:
            - PERSISTENCE_URL=http://persistence:5000

networks:
    notebookum-network:
        external: true
